version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: always
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/file

  localstack:
    image: localstack/localstack
    container_name: localstack
    restart: always
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT=1
    volumes:
      - localstack-data:/var/lib/localstack

volumes:
  mongo-data:
  vault-data:
  localstack-data: